name: mymitra
description: "a mitra project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  shared_preferences: ^2.5.2
  path_provider: ^2.1.5
  fluttertoast: ^8.2.8
  google_mlkit_face_detection: ^0.13.1
  vibration: ^3.1.3
  audioplayers: ^6.4.0
  geolocator: ^13.0.3
  safe_device: ^1.2.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  http: ^1.3.0
  dynamic_color: ^1.7.0
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/face.png
    - assets/sounds/beep.mp3
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"